/**
 * Ranks each AP Toolbox Pro departure by its standalone marginal EV: paired
 * shoe sessions (same shuffle seed for both policies, so hands neither policy
 * treats differently contribute zero noise up to the point they first
 * diverge) comparing "catalog = [this row only]" against a no-index
 * baseline, on a 1-12 spread ramp so a play's value is weighted the way it's
 * actually realized (disproportionately at high counts). Each session runs
 * HANDS_PER_SHOE hands so true counts actually reach the depths most indexed
 * plays trigger at — a single fresh-shoe hand starts at TC 0 and almost never
 * reaches them, which under-samples every play to near zero.
 *
 * These are standalone marginal contributions, not a greedy/interactive
 * ranking — two plays that overlap (e.g. 16 v 9 stand vs surrender) each get
 * measured independently, which is fine for sorting a reference sheet but
 * would double-count if summed. Run: npx tsx scripts/rankDeviations.ts
 */
import { writeFileSync } from "node:fs";
import { DEFAULT_ADVANTAGE_RULES, RAMPS } from "../lib/blackjack/advantage";
import { Deviation } from "../lib/blackjack/deviations";
import { H17_PRO_DEVIATIONS } from "../lib/blackjack/apToolboxH17Pro";
import { S17_PRO_DEVIATIONS } from "../lib/blackjack/apToolboxS17Pro";
import { DeviationGroup, simulateShoeSession } from "../lib/blackjack/shoeSimulation";

const TRIALS_PER_ROW = 50_000;
const HANDS_PER_SHOE = 60;

async function pairedMarginalEv(catalogRow: Deviation, rules: typeof DEFAULT_ADVANTAGE_RULES): Promise<number> {
  let diffSum = 0;
  let hands = 0;
  for (let i = 0; i < TRIALS_PER_ROW; i++) {
    const seed = i + 1;
    const config = {
      bankroll: 1e9, bettingUnit: 1, playerHands: 1, roundsPerHour: 100,
      handsToSimulate: HANDS_PER_SHOE, highSpeed: true, rules, ramp: RAMPS["1-12"], deviationGroups: [] as DeviationGroup[],
    };
    const [base, treatment] = await Promise.all([
      simulateShoeSession({ ...config, seed, catalogOverride: [] }),
      simulateShoeSession({ ...config, seed, catalogOverride: [catalogRow] }),
    ]);
    diffSum += treatment.totalProfit - base.totalProfit;
    hands += base.totalHands;
  }
  return diffSum / hands;
}

async function rankCatalog(label: string, catalog: readonly Deviation[], dealerHitsSoft17: boolean) {
  const rules = { ...DEFAULT_ADVANTAGE_RULES, dealerHitsSoft17 };
  const results: { id: string; hand: string; dealer: string; marginalEvPer100: number }[] = [];
  for (const row of catalog) {
    const started = Date.now();
    const evPerHand = await pairedMarginalEv(row, rules);
    const id = (row as { id?: string }).id ?? `${row.hand}-${row.dealer}-${row.index}`;
    results.push({ id, hand: row.hand, dealer: row.dealer, marginalEvPer100: evPerHand * 100 });
    console.log(`[${label}] ${row.hand} v ${row.dealer} (${id}): ${(evPerHand * 100).toFixed(4)}% per 100 hands (${Date.now() - started}ms)`);
  }
  return results;
}

async function main() {
  const started = Date.now();
  const h17 = await rankCatalog("H17", H17_PRO_DEVIATIONS, true);
  const s17 = await rankCatalog("S17", S17_PRO_DEVIATIONS, false);
  const payload = {
    metadata: {
      generatedUtc: new Date().toISOString(),
      trialsPerRow: TRIALS_PER_ROW,
      handsPerShoe: HANDS_PER_SHOE,
      method: "paired shoe sessions (shared shuffle seed per policy pair, 60 hands/shoe), 1-12 ramp, 6D/4.5 dealt, standalone marginal EV vs a no-index baseline",
      limit: "standalone marginal EVs; overlapping plays are not additive and interactions between plays are not modeled",
    },
    h17,
    s17,
  };
  writeFileSync(
    new URL("../lib/blackjack/deviationRanking.generated.json", import.meta.url),
    JSON.stringify(payload, null, 2) + "\n",
  );
  const lines = [
    "// Generated by ../scripts/rankDeviations.ts. Do not edit by hand; regenerate the artifact.",
    "export const DEVIATION_RANKING_METADATA = " + JSON.stringify(payload.metadata, null, 2) + " as const;",
    "export const DEVIATION_RANKING: Record<string, number> = {",
    ...[...h17, ...s17].map((row) => `  "${row.id}": ${row.marginalEvPer100.toFixed(6)},`),
    "};",
    "",
  ];
  writeFileSync(new URL("../lib/blackjack/deviationRanking.ts", import.meta.url), lines.join("\n"));
  console.log(`Done in ${((Date.now() - started) / 1000).toFixed(0)}s`);
}

main();
