/**
 * Prices every Pro departure and regenerates
 * `lib/blackjack/deviationRanking.ts`.
 *
 * The measurement is the conditional EV difference at the decision point; see
 * `lib/blackjack/deviationEv.ts` for why session-differencing cannot resolve
 * numbers this small and what the estimator does instead.
 *
 * Four profiles are produced, because whether the table offers late surrender
 * changes which rows do anything at all: the chart's starred stand indices are
 * live only where surrender is unavailable, and its surrender rows only where
 * it is.
 *
 * Rows that are dormant by construction, and are expected to come back as
 * [0, 0, 0] from any future run:
 *
 * - `h17Pro-16v10-R`, `h17Pro-16vA-R` and, since basic strategy moved onto the
 *   chart tables, `s17Pro-16vA-R`. Each is an unconditional late surrender of a
 *   cell basic strategy already surrenders at every count, so the departure
 *   never changes a play and has nothing to price. `s17Pro-16vA-R` last
 *   measured 0.0245 units/100 over 0.318 triggers/100 against the previous
 *   branch-based engine, which gated that surrender behind H17; the artifact
 *   was patched to zeros rather than re-measured when that gate was removed.
 *
 * The committed artifact will NOT reproduce exactly on a re-run, for a reason
 * beyond that one patched row. It was measured while basic strategy still
 * returned "D" for a hand that had already drawn — the branch-based engine did
 * not consider card count — and `playBox` in `deviationEv.ts` coerces
 * anything that is not "S" to "H" once a hand is drawing. A drawn soft 18
 * versus a 2 therefore hit
 * where the chart stands, on every profile, throughout the committed run. Basic
 * strategy now demotes those cells to their own fallback, so a regeneration
 * autoplays them correctly and every row shifts slightly. The effect is
 * second-order and expected to sit inside the published intervals, but it is
 * not covered by `DEVIATION_RANKING_METADATA.limit`.
 *
 * Run: npx tsx scripts/rankDeviations.ts [rounds] [replications]
 */
import { writeFileSync } from "node:fs";
import { DEFAULT_ADVANTAGE_RULES, RAMPS } from "../lib/blackjack/advantage";
import { H17_PRO_DEVIATIONS } from "../lib/blackjack/h17Pro";
import { S17_PRO_DEVIATIONS } from "../lib/blackjack/s17Pro";
import { DeviationEvRow, measureDeviationEv } from "../lib/blackjack/deviationEv";

const ROUNDS = Number(process.argv[2] ?? 40_000_000);
const REPLICATIONS = Number(process.argv[3] ?? 300);
const RAMP = "1-12" as const;

const PROFILES = [
  { key: "h17-ls", label: "H17, late surrender", dealerHitsSoft17: true, lateSurrender: true },
  { key: "h17-no-ls", label: "H17, no surrender", dealerHitsSoft17: true, lateSurrender: false },
  { key: "s17-ls", label: "S17, late surrender", dealerHitsSoft17: false, lateSurrender: true },
  { key: "s17-no-ls", label: "S17, no surrender", dealerHitsSoft17: false, lateSurrender: false },
] as const;

function run(profile: (typeof PROFILES)[number]): DeviationEvRow[] {
  const started = Date.now();
  const rows = measureDeviationEv({
    rules: {
      ...DEFAULT_ADVANTAGE_RULES,
      dealerHitsSoft17: profile.dealerHitsSoft17,
      lateSurrender: profile.lateSurrender,
    },
    ramp: RAMPS[RAMP],
    rounds: ROUNDS,
    replications: REPLICATIONS,
    seed: 20260821,
    catalog: profile.dealerHitsSoft17 ? H17_PRO_DEVIATIONS : S17_PRO_DEVIATIONS,
  });
  const live = rows.filter((row) => row.triggersPer100 > 0);
  const worstError = Math.max(0, ...live.map((row) => 1.96 * row.standardError));
  console.log(
    `[${profile.key}] ${live.length}/${rows.length} rows live · ` +
    `total ${rows.reduce((sum, row) => sum + row.evPer100, 0).toFixed(4)} units/100 · ` +
    `widest 95% interval ±${worstError.toFixed(4)} · ${((Date.now() - started) / 1000).toFixed(0)}s`,
  );
  return rows;
}

const results = Object.fromEntries(PROFILES.map((profile) => [profile.key, run(profile)]));

const metadata = {
  generatedUtc: new Date().toISOString(),
  rounds: ROUNDS,
  replications: REPLICATIONS,
  ramp: RAMP,
  game: "6 decks, 75% dealt, DAS, RSA, 3:2, one spot",
  method:
    "conditional EV at the decision point: every round where the departure changes the play is replayed under both actions against an identical dealer hand and identical player draws from the true remaining shoe, and the difference is weighted by the wager the ramp had out",
  limit:
    "standalone marginal values against a basic-strategy baseline. Overlapping cells are measured independently, and a departure's effect on later rounds in the same shoe is not modelled",
};

const payload = { metadata, profiles: PROFILES, results };
writeFileSync(
  new URL("../lib/blackjack/deviationRanking.generated.json", import.meta.url),
  JSON.stringify(payload, null, 2) + "\n",
);

const lines = [
  "// Generated by ../scripts/rankDeviations.ts. Do not edit by hand; regenerate the artifact.",
  "export const DEVIATION_RANKING_METADATA = " + JSON.stringify(metadata, null, 2) + " as const;",
  "",
  "/** Dealer rule and surrender availability both change which departures do anything. */",
  "export type DeviationRankingProfile = " + PROFILES.map((profile) => `"${profile.key}"`).join(" | ") + ";",
  "",
  "export const DEVIATION_RANKING_PROFILE_LABELS: Record<DeviationRankingProfile, string> = {",
  ...PROFILES.map((profile) => `  "${profile.key}": ${JSON.stringify(profile.label)},`),
  "};",
  "",
  "/** [units per 100 rounds, standard error, rounds per 100 in which the play changes]. */",
  "export type DeviationRankingEntry = readonly [evPer100: number, standardError: number, triggersPer100: number];",
  "",
  "export const DEVIATION_RANKING: Record<DeviationRankingProfile, Record<string, DeviationRankingEntry>> = {",
  ...PROFILES.flatMap((profile) => [
    `  "${profile.key}": {`,
    ...results[profile.key].map(
      (row) => `    "${row.id}": [${row.evPer100.toFixed(6)}, ${row.standardError.toFixed(6)}, ${row.triggersPer100.toFixed(4)}],`,
    ),
    "  },",
  ]),
  "};",
  "",
];
writeFileSync(new URL("../lib/blackjack/deviationRanking.ts", import.meta.url), lines.join("\n"));
console.log("Wrote lib/blackjack/deviationRanking.ts");
