"use client";

import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Metric, Panel } from "./ui";
import type { AdvancedData, AlertRow, OrderedFunnelRow, SegmentedCohortRow } from "./AdminPage";

const tooltipStyle = { background: "#111", border: "1px solid #333", borderRadius: 10 };
const displayName = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const percent = (value: number | null | undefined) => value == null ? "—" : `${Number(value).toFixed(1)}%`;
const duration = (value: number | null | undefined) => {
  if (!value) return "0s";
  const seconds = Math.round(value / 1000);
  return seconds < 60 ? `${seconds}s` : `${Math.floor(seconds / 60)}m ${seconds % 60}s`;
};

function SectionTitle({ title, note }: { title: string; note?: string }) {
  return <div className="mb-5 flex flex-wrap items-end justify-between gap-2"><h2 className="text-lg font-semibold">{title}</h2>{note && <p className="text-xs text-zinc-500">{note}</p>}</div>;
}

function Table({ rows, columns }: { rows: Array<Record<string, unknown>>; columns: Array<{ key: string; label: string; format?: (value: unknown) => string | number }> }) {
  if (!rows.length) return <p className="py-8 text-center text-sm text-zinc-500">No data for this period.</p>;
  return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-zinc-500"><tr>{columns.map((column) => <th key={column.key} className="whitespace-nowrap pb-3 pr-4 font-medium">{column.label}</th>)}</tr></thead><tbody>{rows.map((row,index) => <tr key={index} className="border-t border-white/[.06]">{columns.map((column,columnIndex) => <td key={column.key} className={`whitespace-nowrap py-3 pr-4 ${columnIndex ? "text-zinc-400" : "font-medium"}`}>{column.format ? column.format(row[column.key]) : String(row[column.key] ?? "—")}</td>)}</tr>)}</tbody></table></div>;
}

const records = <T extends object>(rows: T[]) => rows as Array<Record<string, unknown>>;

export function AdminAdvancedAnalytics({ advanced, cohorts, funnel, alerts, cohortDimension }: {
  advanced: AdvancedData;
  cohorts: SegmentedCohortRow[];
  funnel: OrderedFunnelRow[];
  alerts: AlertRow[];
  cohortDimension: string;
}) {
  return <>
    <Panel className="mt-6"><SectionTitle title="North-star metric" note="Weekly returning users completing at least one training session" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Profiles" value={advanced.identity.profiles} sub={`${advanced.identity.authenticated} authenticated`} /><Metric label="Returning" value={advanced.identity.returning} sub={`${advanced.identity.resurrected} resurrected`} /><Metric label="Avg active days" value={advanced.identity.avg_active_days?.toFixed(1) ?? "0"} /><Metric label="Avg sessions / user" value={advanced.identity.avg_sessions?.toFixed(1) ?? "0"} /><Metric label="Power users" value={advanced.power_users?.users ?? 0} sub={`Top-10% threshold ${advanced.power_users?.threshold ?? 0}`} /></div><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={advanced.north_star}><CartesianGrid stroke="#ffffff0d" /><XAxis dataKey="week" stroke="#71717a" tickFormatter={(value) => String(value).slice(5,10)} /><YAxis stroke="#71717a" allowDecimals={false} /><Tooltip contentStyle={tooltipStyle} /><Line type="monotone" dataKey="returning_users_completing_training" name="Returning training users" stroke="#b5ed5c" strokeWidth={2} /><Line type="monotone" dataKey="completed_training_sessions" name="Completed sessions" stroke="#38bdf8" strokeWidth={2} /></LineChart></ResponsiveContainer></div></Panel>

    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel><SectionTitle title="Lifecycle" note="Active, slipping, churned, and resurrected" /><Table rows={records(advanced.lifecycle)} columns={[{ key:"lifecycle_state",label:"State",format:(value)=>displayName(String(value)) },{ key:"users",label:"Users" },{ key:"resurrected",label:"Resurrected" }]} /></Panel><Panel><SectionTitle title="Activation milestones" note="Average time from first seen" /><Table rows={records(advanced.activation)} columns={[{ key:"milestone",label:"Milestone",format:(value)=>displayName(String(value)) },{ key:"users",label:"Users" },{ key:"avg_minutes_to_milestone",label:"Avg time",format:(value)=>value==null?"—":duration(Number(value)*60000) }]} /></Panel></div>

    <Panel className="mt-6"><SectionTitle title="Ordered arbitrary funnel" note="Every step occurs after the prior step for the same visitor" /><Table rows={records(funnel)} columns={[{ key:"step",label:"Step" },{ key:"event",label:"Event",format:(value)=>displayName(String(value)) },{ key:"users",label:"Users" },{ key:"conversion_from_prior",label:"Conversion",format:(value)=>percent(value as number|null) },{ key:"median_ms_from_prior",label:"Median time",format:(value)=>duration(value as number|null) }]} /></Panel>

    <Panel className="mt-6"><SectionTitle title={`Segmented retention · ${displayName(cohortDimension)}`} note="Exact-day and windowed retention" /><Table rows={records(cohorts.slice(0,80))} columns={[{ key:"cohort_week",label:"Cohort",format:(value)=>String(value).slice(0,10) },{ key:"segment",label:"Segment",format:(value)=>displayName(String(value)) },{ key:"cohort_size",label:"Users" },{ key:"d1",label:"D1",format:(value)=>percent(value as number|null) },{ key:"d7",label:"D7",format:(value)=>percent(value as number|null) },{ key:"d30",label:"D30",format:(value)=>percent(value as number|null) },{ key:"week_1",label:"Week 1",format:(value)=>percent(value as number|null) },{ key:"month_1",label:"Month 1",format:(value)=>percent(value as number|null) }]} /></Panel>

    <Panel className="mt-6"><SectionTitle title="Feature adoption and retention" note="Time-to-use, repetition, same-feature retention, and abandonment" /><Table rows={records(advanced.adoption)} columns={[{ key:"feature",label:"Feature",format:(value)=>displayName(String(value)) },{ key:"users",label:"Users" },{ key:"avg_hours_to_first_use",label:"Hours to first",format:(value)=>value==null?"—":Number(value).toFixed(1) },{ key:"uses_per_user",label:"Uses/user" },{ key:"repeat_rate",label:"Repeat",format:(value)=>percent(value as number) },{ key:"week_1_retention",label:"Week 1",format:(value)=>percent(value as number) },{ key:"month_1_retention",label:"Month 1",format:(value)=>percent(value as number) },{ key:"abandonment_rate",label:"Abandoned",format:(value)=>percent(value as number) }]} /></Panel>

    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel><SectionTitle title="Training mastery" note="Accuracy × evidence × recency" /><Table rows={records(advanced.mastery)} columns={[{ key:"drill",label:"Drill",format:(value)=>displayName(String(value)) },{ key:"users",label:"Users" },{ key:"recent_accuracy",label:"Accuracy",format:(value)=>percent(value as number) },{ key:"median_response_ms",label:"Median",format:(value)=>duration(value as number) },{ key:"avg_mastery",label:"Mastery",format:(value)=>percent(value as number) },{ key:"mastered_users",label:"Mastered",format:(value)=>percent(value as number) }]} /></Panel><Panel><SectionTitle title="Streak distribution" /><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={advanced.streaks}><CartesianGrid stroke="#ffffff0d" /><XAxis dataKey="streak_bucket" stroke="#71717a" /><YAxis stroke="#71717a" allowDecimals={false} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="answers" fill="#1e8f62" radius={[5,5,0,0]} /></BarChart></ResponsiveContainer></div></Panel></div>

    <Panel className="mt-6"><SectionTitle title="Scenario speed and accuracy" note="Fastest/slowest correct medians with P90 tail" /><Table rows={records(advanced.scenarios_advanced)} columns={[{ key:"drill",label:"Drill",format:(value)=>displayName(String(value)) },{ key:"scenario",label:"Scenario" },{ key:"attempts",label:"Attempts" },{ key:"accuracy",label:"Accuracy",format:(value)=>percent(value as number) },{ key:"correct_median_ms",label:"Correct median",format:(value)=>duration(value as number|null) },{ key:"p90_ms",label:"P90",format:(value)=>duration(value as number) }]} /></Panel>

    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel><SectionTitle title="Common journeys" note="First eight high-level events" /><Table rows={records(advanced.journeys)} columns={[{ key:"path",label:"Path" },{ key:"sessions",label:"Sessions" },{ key:"success_rate",label:"Success",format:(value)=>percent(value as number) }]} /></Panel><Panel><SectionTitle title="Route transitions" /><Table rows={records(advanced.transitions)} columns={[{ key:"from_path",label:"From" },{ key:"to_path",label:"To" },{ key:"mechanism",label:"Mechanism",format:(value)=>displayName(String(value)) },{ key:"transitions",label:"Count" }]} /></Panel></div>

    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel><SectionTitle title="Workflow abandonment" note="Derived at session boundaries" /><div className="grid gap-3 sm:grid-cols-2"><Metric label="Practice · no answer" value={advanced.abandonment.practice_started_no_answer} /><Metric label="Answered · no completion" value={advanced.abandonment.practice_answered_no_completion} /><Metric label="Calculator · no run" value={advanced.abandonment.calculator_opened_no_run} /><Metric label="Signup · no completion" value={advanced.abandonment.signup_started_no_completion} /></div></Panel><Panel><SectionTitle title="Returning-session first action" /><Table rows={records(advanced.return_behavior)} columns={[{ key:"first_action",label:"Action",format:(value)=>displayName(String(value)) },{ key:"sessions",label:"Sessions" }]} /></Panel></div>

    <Panel className="mt-6"><SectionTitle title="Derived UI friction" note="Repeated back navigation, actions, validation failures, and rapid bouncing" /><Table rows={records(advanced.friction_derived ?? [])} columns={[{ key:"kind",label:"Signal",format:(value)=>displayName(String(value)) },{ key:"path",label:"Route" },{ key:"element",label:"Element",format:(value)=>displayName(String(value)) },{ key:"occurrences",label:"Occurrences" },{ key:"affected_sessions",label:"Sessions" }]} /></Panel>

    <Panel className="mt-6"><SectionTitle title="Entry, exit, and repeat page use" /><Table rows={records(advanced.pages_advanced)} columns={[{ key:"path",label:"Route" },{ key:"views",label:"Views" },{ key:"visitors",label:"Visitors" },{ key:"repeat_visitors",label:"Repeat visitors" },{ key:"entries",label:"Entries" },{ key:"exits",label:"Exits" }]} /></Panel>

    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel><SectionTitle title="Educational content" /><Table rows={records(advanced.content)} columns={[{ key:"content",label:"Content",format:(value)=>displayName(String(value)) },{ key:"opens",label:"Opens" },{ key:"completion_rate",label:"Completion",format:(value)=>percent(value as number) },{ key:"feature_launches",label:"Feature launches" },{ key:"avg_reading_ms",label:"Reading time",format:(value)=>duration(value as number|null) }]} /></Panel><Panel><SectionTitle title="Calculator behavior" /><Table rows={records(advanced.calculators)} columns={[{ key:"calculator",label:"Calculator",format:(value)=>displayName(String(value)) },{ key:"opens",label:"Opens" },{ key:"input_changes",label:"Inputs" },{ key:"runs",label:"Runs" },{ key:"repeats",label:"Repeats" },{ key:"repeat_users",label:"Repeat users" }]} /></Panel></div>

    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel><SectionTitle title="Experiments" note="Exposure, conversion, and error guardrails" /><Table rows={records(advanced.experiments)} columns={[{ key:"experiment",label:"Experiment" },{ key:"variant",label:"Variant" },{ key:"users",label:"Users" },{ key:"conversion_rate",label:"Conversion",format:(value)=>percent(value as number) },{ key:"users_with_errors",label:"Users with errors" }]} /></Panel><Panel><SectionTitle title="Feature-flag exposure" note="Effective variation seen by each user" /><Table rows={records(advanced.feature_flags)} columns={[{ key:"flag",label:"Flag" },{ key:"variation",label:"Variation" },{ key:"users",label:"Users" },{ key:"users_with_errors",label:"Users with errors" }]} /></Panel></div>

    {alerts.length > 0 && <Panel className="mt-6"><SectionTitle title="Operational alerts" note="Webhook delivery uses the scheduled analytics-alerts Edge Function" /><Table rows={records(alerts)} columns={[{ key:"metric",label:"Metric",format:(value)=>displayName(String(value)) },{ key:"value",label:"Current",format:(value)=>value==null?"—":Number(value).toFixed(2) },{ key:"threshold",label:"Threshold" },{ key:"triggered",label:"Status",format:(value)=>value?"Triggered":"Healthy" },{ key:"delivery_count",label:"Deliveries" },{ key:"last_sent_at",label:"Last sent",format:(value)=>value?new Date(String(value)).toLocaleString():"Never" }]} /></Panel>}
  </>;
}
