"""Generate the no-index (basic-strategy) counterpart of the production coefficients.

The production run in `simulate.py --all` measures the game with the documented
Hi-Lo index set switched on. The app also offers a "Deviations" skill setting
(Beginner / Intermediate / Pro / Perfect), which needs to price a player who
only captures part of the index EV.

Doing that honestly requires knowing the edge at every true count with indices
switched OFF, so the two measured curves can be interpolated:

    advantage(skill) = noIndex + skill * (withIndex - noIndex)

which is exact at skill 0 and skill 1 and monotone between them. Without the
no-index curve the app has to shrink toward some invented anchor, which produces
nonsense at the extremes (a +8 shoe is worth +4.2% to a pure basic-strategy
player, not the near-zero value a neutral-count anchor implies).

`simulate.py --validate` already measures this, but only for 6 decks / 4.5 dealt.
This script runs the same audited `run_configuration` code path with
`use_indices=False` across all nine production deck/penetration profiles.

It deliberately does not modify `simulate.py`: that file's SHA-256 is recorded
inside the production artifacts, and `tests/test_artifact.py` binds them
together. Importing its functions keeps that chain intact.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
from datetime import datetime, timezone
from pathlib import Path

import numba
import numpy as np

from simulate import (
    GAME_OPTIONS,
    Z95,
    git_metadata,
    run_configuration,
    simulate_parallel,
    strategy_manifest,
)


def normalized_sha256(path: Path) -> str:
    """SHA-256 of a source file with line endings normalized to LF.

    Git checks these files out with CRLF on Windows, so hashing raw bytes would
    record a machine-dependent provenance hash. Normalizing keeps the recorded
    value comparable to the hashes stored with the production coefficients.
    """
    return hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


TYPESCRIPT_HEADER = '''// Generated by ../blackjack-simulator/noindex.py.
// Do not edit these coefficients by hand; regenerate them from the audited JSON.
//
// The same nine deck/penetration profiles as RAW_COEFFICIENTS, but measured with
// the Hi-Lo index set switched off. Interpolating between the two tables is what
// lets the app price partial deviation skill without inventing an anchor.
import type { RawCoefficient } from "./coefficients";
'''


def number(value: float) -> str:
    return format(value, ".12g")


def write_typescript(payload: dict, destination: Path) -> None:
    lines = [TYPESCRIPT_HEADER]
    metadata = payload["metadata"]
    total_rounds = sum(profile["rounds"] for profile in payload["profiles"].values())
    lines.extend([
        "export const NO_INDEX_METADATA = {",
        f'  generatedUtc: "{metadata["created_utc"]}",',
        f'  sourceSha256: "{metadata["source_sha256"]}",',
        f'  simulateSourceSha256: "{metadata["simulate_source_sha256"]}",',
        f'  seed: {metadata["seed"]},',
        f'  shoesPerProfile: {metadata["requested_shoes_per_configuration"]},',
        f"  totalRounds: {total_rounds},",
        '  model: "6/8 deck | H17 | DAS | RSA | LS | peek | 3:2 | one spot | '
        'basic strategy only, no index departures and no insurance",',
        "} as const;",
        "export const NO_INDEX_COEFFICIENTS: Record<string, readonly RawCoefficient[]> = {",
    ])
    for key, profile in payload["profiles"].items():
        lines.append(f'  "{key}": [')
        for row in profile["rows"]:
            lines.append(
                "    ["
                + ", ".join((
                    number(row["frequency"]),
                    number(row["advantage"]),
                    number(row["standard_deviation"]),
                    str(row["rounds"]),
                    number(row["standard_error"]),
                ))
                + "],"
            )
        lines.append("  ],")
    lines.append("};")
    lines.append("")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Simulate the no-index counterpart of the production coefficients",
    )
    parser.add_argument("--shoes", type=int, default=100_000_000)
    parser.add_argument("--tasks", type=int, default=max(1, os.cpu_count() or 1))
    parser.add_argument("--seed", type=int, default=20260817)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--typescript", type=Path)
    args = parser.parse_args()

    # Compile before timing any configuration.
    simulate_parallel(
        6, 4.5, np.array([1], dtype=np.int64), np.array([1], dtype=np.int64), False, 1,
    )

    results = {}
    for decks, values in GAME_OPTIONS.items():
        for dealt in values:
            print(
                f"Simulating {decks}D, {dealt:g} dealt, indices=False, "
                f"shoes={args.shoes:,} ...",
                flush=True,
            )
            result = run_configuration(
                decks, dealt, args.shoes, args.tasks, args.seed,
                use_indices=False, spots=1,
            )
            results[f"{decks}-{dealt:g}"] = result
            print(
                f"  {result['rounds']:,} rounds in {result['runtime_seconds']:.1f}s; "
                f"EV {result['mean']:+.6%} +/- {Z95 * result['standard_error']:.6%} (95%); "
                f"SD {result['standard_deviation']:.6f}",
                flush=True,
            )

    payload = {
        "metadata": {
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "source_sha256": normalized_sha256(Path(__file__)),
            "simulate_source_sha256": normalized_sha256(
                Path(__file__).parent / "simulate.py",
            ),
            "git": git_metadata(),
            "python": platform.python_version(),
            "numpy": np.__version__,
            "numba": numba.__version__,
            "platform": platform.platform(),
            "cpu_count": os.cpu_count(),
            "requested_shoes_per_configuration": args.shoes,
            "tasks": args.tasks,
            "seed": args.seed,
            "spots": 1,
            "use_indices": False,
            "strategy": {
                **strategy_manifest(),
                "note": (
                    "Index departures and insurance are disabled for this run; only "
                    "the basic-strategy core of choose_action() is exercised."
                ),
            },
        },
        "profiles": results,
    }
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {args.output}")
    if args.typescript:
        write_typescript(payload, args.typescript)
        print(f"Wrote {args.typescript}")


if __name__ == "__main__":
    main()
